# Generated by Django 5.1.3 on 2024-11-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=500)),
            ],
        ),
    ]
